### ISSUE TITLE
Why doesn't this project take off in a big way?

### ISSUE THREAD

**Issue by gabriel-r** [hamiltop/MongoLiteDB#3]
This idea and project are amazing, why does't it take off in a big way? 

I just started searching for such a solution, maybe I missed something elsewhere?

**Comment by gabriel-r** [comment]
PS: Last commit …8 years ago. How are you doing @hamiltop? :-)

**Comment by hamiltop** [comment]
I'm doing great. This was a small weekend project that never proved itself useful in anything close to a production environment, but was a good learning experience.

If I were to redo this I would probably just build a layer between sqlite json and the mongo query language if mongo compatibility was absolutely necessary. Otherwise I'd just use sqlite json.

**Comment by gabriel-r** [comment]
Thanks for the update. Maybe what I need is sqlite json, I'll look into it. 
Have a great new year!
